### ISSUE TITLE
Support for no or multiple plugins

### ISSUE THREAD

**Issue by dtzar** [Duffney/notary-sign-action#1]
It would be good to have a plugin switch/var to support additional notation plugins to work with the action OR no plugin and just using notation as-is / local signing.  If the "local" option was specified then people wouldn't have to specify the Azure ENV vars, for instance.

**Comment by duffney** [comment]
Great suggestion! I'll start working on some conditional logic for a no plugin option. :)

**Comment by dtzar** [comment]
Spoke with the notary working group this am and after this plugin is more vendor agnostic (i.e. you can use just notation with or without Azure KV plugin) then we can migrate it there.

**Comment by duffney** [comment]
That's excellent news! And thank you for mentioning this to the working group. I've made some good progress on making the action vendor agnostic and will have some public changes soon.

**Comment by duffney** [comment]
@dtzar I've updated the action and abstracted the setup logic to [another GitHub action](https://github.com/Duffney/setup-notation). That action handles the install of notation and any plugins. It also sets the cert that configured with the setup as the default, making this action a simple notation sign command. I imagine over this sign action will grow more complex allowing for different keys to be used and possibly adding verify logic as well.  Please lmk what you think. :)
