### ISSUE TITLE
Support --envelope-type cose

### ISSUE THREAD

**Issue by dtzar** [Duffney/notary-sign-action#3]

**Comment by duffney** [comment]
I think adding an args input parameter to the action would be the best way to add this functionality. I'll investigate how that could be done with the composite action, but I'll likely convert it to a JavaScript action to add that functionality. Thanks for the feedback. :)

**Comment by duffney** [comment]
I've added an args input param to the action that will let you pass in any args you'd like to the notation CLI. Please lmk what you think. :)

**Comment by dtzar** [comment]
Recommend updating the readme to the official action and archive this repo :)

**Comment by duffney** [comment]
@dtzar added to my todos for the week. Thanks for the nudge. :)
